### ISSUE TITLE
Mutable/Immutable

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/cookie#1]
Should the cookie be mutable or immutable? (I prefer the latter)

Should it be modifiable at all?

/cc @ddeboer

**Comment by ddeboer** [comment]
If you want modification, definitely immutable. To model it PSR-7 style, you could have something like `withName()`, `withValue()` etc. I guess this makes creating cookies that are a lot alike somewhat easier than passing in all arguments to the constructor over and over again.

**Comment by sagikazarmark** [comment]
Name is a required argument for a cookie, so it should not be modified after set. The rest is optional even in the ctor.

Currently I wonder if modify should be possible. I am not against it, just looking for use cases.
