### ISSUE TITLE
Single CookieJar implementation

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/cookie#4]
Currently we support multiple implementations through an interface. I wonder if we need that?

We could provide a single class for the Jar and provide an interface for persistence, but I am not sure that we need that. IMO a Jar can just be persisted (if needed at all) in whatever way a framework allows (for example using an event, like kernel.shutdown)

This should be resolved prior to moving to php-http/message.

**Comment by joelwurtz** [comment]
IMO, we should provide a in memory implementation and keep this interface if someone wants one day to persist cookie in a database of some king, current interface make sense in this way to have optimized query.

**Comment by sagikazarmark** [comment]
My idea is to remove persisting from the CookieJar. Like moving from Active Record to Data Mapper.

**Comment by sagikazarmark** [comment]
There could still be some kind of CookieJarPersister interface, but not sure if that makes any difference.

**Comment by joelwurtz** [comment]
IMO CookieJar is already a Data Mapper, like addCookie will add the cookie to a storage implementation, it is not the current view ?

**Comment by sagikazarmark** [comment]
Hm. I think CookieJar is rather a collection than a storage layer.

If the CookieJar was the persistence layer, the 90% of implementation would still be the same (see the CookieJarTemplate)

**Comment by sagikazarmark** [comment]
> like addCookie will add the cookie to a storage implementation, it is not the current view ?

No, addCookie currently adds the cookie to a local storage (array or SplObjectStorage). There is a PersistentCookieStorage interface, which IMO makes the CookieJar something like ActiveRecord.

I think it would be better to have a storage interface if necessary:

``` php
interface CookieJarPersistence
{
    public function save(CookieJar $cookieJar);
    public function load();
}
```

Do we really need this functionality INSIDE the cookiejar? Calling any of the methods during the application flow would actually be a huge mistake. Loading/saving should be done through some hooks for example (startup/shutdown events).

**Comment by joelwurtz** [comment]
So if CookieJar is just a collection, we don't need an interface (like you said first). And like @dbu suggest we don't need to provide support for persistence.

**Comment by dbu** [comment]
if there is no more interface,i am force to extend the provided jar for persistence. why do we drop the interface?

**Comment by sagikazarmark** [comment]
You don't need persistence inside the Jar IMO. If you want to persist the cookies, you can do it by having a custom service which accepts a jar instance, loops through it, and saves the data. For loading, you can just load the cookies and set them in a new jar instance and return it.

**Comment by dbu** [comment]
ah, that makes sense. we should mention that in the doc.
